#---------------------------------#
#      environment configuration  #
#---------------------------------#

version: 0.1.0.{build}
environment:
  PSGalleryAPIKey:
    secure: lbDrWTaiRIaEUnUacZbYJHSaCGvAZfz8HsfoaE5uc5NuoebPCvptrlXzRTHN10v9

install:
  - ps: |
      Write-Verbose -Message "PowerShell version $($PSVersionTable.PSVersion)" -Verbose
      Install-Module -Name 'Invoke-Build' -Force
      Install-Module -Name 'platyPS' -Force
      Install-Module -Name 'Pester' -Force
      Install-Module -Name 'PSScriptAnalyzer' -Force

#---------------------------------#
#      build configuration        #
#---------------------------------#

before_build:
  - ps: |
      Import-Module -Name 'Invoke-Build'
      Import-Module -Name 'platyPS'
      Import-Module -Name 'Pester'
      Import-Module -Name 'PSScriptAnalyzer'

build_script:
  - ps: |
      Invoke-Build -Task Build

#---------------------------------#
#      test configuration         #
#---------------------------------#

test_script:
  - ps: |
      Invoke-Build -Task Test

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

before_deploy:
  - ps: |
      ${env:ReleaseNotes} = ( Import-Module $env:APPVEYOR_BUILD_FOLDER -Force -PassThru ).ReleaseNotes

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: $(ReleaseNotes)
    auth_token:
      secure: H6HQrXUd6e0XBLfgdcrQ7T78c3+NTlMF92eBHy79j9W1n20zW8uJDNKzk0v82VM9
    artifact:
    draft: false
    prerelease: false
    force_update: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true

deploy_script:
  - ps: |
      $ErrorActionPreference = 'Continue'
      $deploy = ( $env:APPVEYOR_REPO_TAG -eq $true )
      if ($deploy)
      {
        Invoke-Build -Task Publish
      }
